# Generated by Django 3.2.16 on 2023-01-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
